### ISSUE TITLE
update-container-image fails to update multiple images

### ISSUE THREAD

**Issue by parkerjm** [CircleCI-Public/kubernetes-orb#10]
### Orb version

using aws-eks orb 0.2.2, which appears to use `circleci/kubernetes@0.3.0`. Posting this issue here since the aws-eks orb just passes the value down to the kubernetes orb untouched and it seems the kubernetes orb isn't supplying it to kubectl correctly.

### What happened

Supplying a list of multiple images delimited by spaces fails to update multiple images. Instead, it attempts to set the first container's image to the entire string that comes after the first = character.

For instance, here's my circleci config.yml snippet:
```
          name: Staging Deploy
          requires:
            - Deploy to staging
          aws-region: us-east-2
          cluster-name: staging
          resource-name: deployment.v1.apps/my-app-staging
          container-image-updates: my-app=my-org/my-app:$CIRCLE_SHA1 my-app-job-runner=my-org/my-app:$CIRCLE_SHA1
          record: true
```

and here is the outcome:

```
Containers:
  my-app:
    Container ID:
    Image:          my-org/my-app:f3c65ebb0602966922eeceb92af37cdf6222d375 my-app-job-runner=my-org/my-app:f3c65ebb060296692
2eeceb92af37cdf6222d375
```

which of course leads to kubernetes image pull failures:
```
Warning  InspectFailed   10s (x5 over 26s)  kubelet, ip-192-168-9-21.us-east-2.compute.internal  Failed to apply default image tag "my-org/my-app:f3c65ebb0602966922eeceb92af37cdf6222d375 my-app-job-runner=my-org/my-app:f3c65ebb0602966922eeceb92af37cdf6222d375": couldn't parse image reference "my-org/my-app:f3c65ebb0602966922eeceb92af37cdf6222d375 my-app-job-runner=my-org/my-app:f3c65ebb0602966922eeceb92af37cdf6222d375": invalid reference format
```

I've tried wrapping the line in quotes or no quotes, but it doesn't seem to make any difference.

The other container retains its original image tag (i.e. is unchanged).

### Expected behavior

I should have both containers updated with the new image tag.
