### ISSUE TITLE
can't run kubectl command

### ISSUE THREAD

**Issue by yongzhang** [CircleCI-Public/kubernetes-orb#41]
My config.yml is really simple:
```
version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.2

workflows:
  version: 2
  ci_build:
    jobs:
      - deploy-image

jobs:
  deploy-image:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kubernetes/install-kubectl:
          kubectl-version: 1.14.8
      - run: kubectl version
```

But everytime it stops at `run`:
```
#!/bin/bash -eo pipefail
kubectl version
/usr/local/bin/kubectl: line 1: syntax error near unexpected token `<'
/usr/local/bin/kubectl: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/1.14.8/bin/linux/amd64/kubectl</Details></Error>'

Exited with code exit status 2
CircleCI received exit code 2
```
I really don't understand what's the issue, please help, thanks.
