### ISSUE TITLE
Opt in feature to substitute env variable references

### ISSUE THREAD

**Issue by bjornharrtell** [CircleCI-Public/kubernetes-orb#47]
I use fx. $CIRCLE_PROJECT_REPONAME in deployment yml and substitute in an earlier custom run step before giving it to fx. kubernetes/create-or-update-resource. It would be nice if such substitution could be a simple opt in feature in this orb instead.

**Comment by brivu** [comment]
Hey @bjornharrtell, 

I'm working on this orb at the moment and would really like to understand your request in greater detail.  Can you please provide me with some build links and/or examples on what you mean? 

Thanks, 
Brian

**Comment by bjornharrtell** [comment]
Hi @brivu, perhaps I can explain better with an example. I currently have this approach

```yaml
- run:
    name: Substitution
    command: |
      sudo apt-get update && sudo apt-get install -y gettext-base
      envsubst < deployment-test.yml > deployment.yml
- kubernetes/install-kubectl
- kubernetes/install-kops
- run: kops export kubecfg --admin
- kubernetes/create-or-update-resource:
    resource-file-path: deployment.yml
```

But I would like to avoid the manual envsubst possibly like this:

```yaml
- kubernetes/install-kubectl
- kubernetes/install-kops
- run: kops export kubecfg --admin
- kubernetes/create-or-update-resource:
    resource-file-path: deployment.yml
    envsubst: true
```
