### ISSUE TITLE
update-container-image command fails due to the new kubectl version

### ISSUE THREAD

**Issue by Coconutcoo** [CircleCI-Public/kubernetes-orb#51]
## Orb version:

0.12.1

## What happened:

While running a typical workflow (one that worked just hours previously), that uses `kubernetes/install-kubectl`, we hit 
```
Flag --record has been deprecated, --record will be removed in the future
error: Invalid dry-run value (false). Must be "none", "server", or "client".
``` 
during `kubernetes/update-container-image`.

Snippet from the config.yml; 
```
      - kubernetes/update-container-image:
          container-image-updates: "graphql-api=docker.io/org/repo:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
          get-rollout-status: true
          resource-name: deployment/graphql-apib
```

Looking at your source, you hit https://storage.googleapis.com/kubernetes-release/release/stable.txt to get the version of kubectl to install, and just today k8s pushed a new version, v1.23.0 (https://github.com/kubernetes/sig-release/tree/master/releases/release-1.23), that fully deprecates the "false" default you're using right now.

## Expected behavior:

It should update the image using an appropriate default, in this case the string "none". You should also be locking the version of kubectl to a specific orb version, rather than blindly grabbing "latest" from a live text file.
