### ISSUE TITLE
Allow to specify custom name

### ISSUE THREAD

**Issue by marcinpietraszek-deliveroo** [CircleCI-Public/kubernetes-orb#59]
## Describe Request:

Currently when one defines multiple resources using the same command exposed in the orb all of them have the same name which degrades readability. Adding new `name` parameter to the commands that would overwrite the default name used currently would improve readability of the pipeline run.

## Examples:

```
steps:
  - kubernetes/create-or-update-resource:
    # no name specified, uses default value
    resource-file-path: resource1.yaml
  - kubernetes/create-or-update-resource:
    name: creating resource2
    resource-file-path: resource2.yaml
  - kubernetes/create-or-update-resource:
    name: creating resource3
    resource-file-path: resource3.yaml
```

## Supporting Documentation Links:

https://circleci.com/developer/orbs/orb/circleci/kubernetes#commands-create-or-update-resource doesn't specify `name` parameter. In the source hardcoded value is visible.
